name: Daily Fortune Telling

on:
  schedule:
    - cron: '10 9 * * *'

jobs:
  run-script:
    runs-on: macos-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python Script
        run: |
          echo 'Run fortune_telling.py'
          python ./script/fortune_telling.py
        env: 
          SECRET_KEY: ${{ secrets.SLACK_LUCKY_DAILY }}